#spring
spring:
  datasource:
    #    参考 https://www.cnblogs.com/crazysquirrel/p/12804517.html
    url: jdbc:h2:file:./db/h2/dev;AUTO_SERVER=TRUE;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
    driver-class-name: org.h2.Driver
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
logging:
  level: debug
  level.name.xu: debug
  path: logs/
project:
  name: '使用 H2 的 spring-boot 项目'

